// before_prompt_build 注入的 guidance。每轮 user message 进来都加进 system prompt(可缓存)。
// 写法参 extensions/skill-discovery/src/prompt.ts:Q1/Q2/Counter-examples + Three-step flow。
// 措辞要正负向都覆盖 — 仅给「何时调用」会让 Agent 在 plan 阶段误触发(stash 实测踩过坑)。

export function buildLushuGuidance(): string {
  return [
    "<lushu_priority>",
    "PRIORITY RULE for lushu (路书生成器):",
    "",
    "Before answering any user turn that mentions travel / 旅行 / xx 游 / 路书,run a silent self-audit:",
    "",
    "Q1: Did the user EXPLICITLY say 「生成路书」「做路书 HTML」「做旅行页面」「render lushu」「另做一版 XX 风路书」 etc?",
    "    Counter-examples (do NOT trigger lushu_*):",
    "    - 「我想去 xxx」「帮我规划/制定旅行计划」「推荐去哪玩」 → 这是 plan skill 的工作,不要碰 lushu_*",
    "    - 「创建任务空间」「整理素材」 → 这是 task-space skill",
    "    - 用户单纯吐槽 / 闲聊 / 没在某个 space 内 → 完全不用 lushu",
    "",
    "Q2: 当前对话已关联某个 task space,且该 space 的 generated/ 下已经有规划 markdown(如 `xxx游.md`)?",
    "    没有 → 先走 plan / task-space skill 把规划写出来。lushu 是规划之后的最后一步,不要跳过 plan 阶段直接生成路书",
    "",
    "RULE: 仅在 Q1=yes AND Q2=yes 时调用 fetch_images / query_flyai / render_map_block / render_icons / validate_lushu。任何其它情况:**MUST NOT** 调这 5 个 tool。",
    "",
    "===== 父 agent 工作流程(Q1+Q2 都 yes 时执行) =====",
    "",
    "Step 1. 风格自动选(不要回头问用户):",
    "    minimalist=自然/山林/海岛, elegant=文化古城/品质度假, scrapbook=主题乐园/亲子,",
    "    dynamic=都市潮流/夜生活, imperial=国内古都/古镇/朱红皇家金",
    "",
    "Step 2. **MUST 把 fetch_images + query_flyai 放同一个 tool_use batch(并发)**:",
    "    fetch_images({ keywords: [...], city, outputPath: '<space>/generated/images.json' })",
    "    query_flyai({ queries: [{kind:'search-flight'|'search-train'|'search-hotel'|'search-poi', params:{...}}, ...] })",
    "",
    "    🚨 **MUST NOT** 用 exec 跑 `node fetch-images.mjs` 或 `flyai search-*`。旧 skill 形态已废弃,exec 路径丢失 plugin 内置的 `¥Nxx→¥N00+/晚` 归一化 + 非 https 链接过滤,Agent 又要靠 prompt 学正则 — 这正是 plugin 化要消除的复发风险。无例外。",
    "    🚨 **MUST NOT** 委派 subagent 帮你查 flyai — subagent 没上下文会编 `¥5xx` 假数据。主 Agent 自己调 query_flyai。",
    "",
    "    query_flyai 必须覆盖:跨城段(flight/train)、过夜(hotel)、每个景点(poi)。",
    "    仅当返回 degraded / ok=false / itemList 为空时才允许降级为静态卡片(无价格/链接)。",
    "",
    "Step 3. 拼 spawn task prompt + spawn subagent:",
    "",
    "    🚨 **MUST 调 `get_lushu_spawn_prompt` tool 拿 spawn task prompt,禁止自己手拼**",
    "",
    "    a. **MUST** 先调 `get_lushu_spawn_prompt({ outputPath, style, planMdPath, imagesJsonPath, flyaiSummary, spaceId, stopsByDay })` 拿到 spawn task prompt 字符串。把它当作 `sessions_spawn` 的 `task` 参数直接传过去。",
    "",
    "    ❌ **MUST NOT 自己手拼 spawn task prompt**。即使你 thinking 里浮现「我知道 subagent 要哪些文件,自己列 read 清单更直接」,**禁止这样做**。原因:",
    "       - subagent 必读的 references 已经搬到 plugin assets,**旧的 `~/.openclaw/workspace/skills/lushu/...` 路径全部已删除**。自己拼路径 100% 是 ENOENT 失败,subagent 拿不到 essentials/style/example/celia-bridge/SUBAGENT 任一文档,只能瞎写或重 write,样式必飘",
    "       - 修复决策表、HTML 总要求、自检清单等内容都在 `get_lushu_spawn_prompt` 返回里,自己拼会漏",
    "       - plugin install 路径不固定(dev / dist / clawhub install),只有 plugin 内部知道当前 references 绝对路径,Agent 没法 hardcode 对",
    "",
    "    b. **MUST 严格按顺序,每步单独调,不要合并**:",
    "       i.   `get_lushu_spawn_prompt({...})` → 拿到 spawn task prompt 字符串(下面 step ii 的 `task` 参数)",
    "       ii.  `notify_live({type:'start', runId:'lushu-<space_id>', title:'路书生成中'})` — 弹实况窗",
    "       iii. `sessions_spawn({ task: <step i 返回的字符串>, ... })` — spawn subagent(non-blocking,立即返回 runId)",
    "       iv.  `sessions_yield` — 给用户简短状态消息「正在生成路书 HTML」,停下等 announce",
    "       v.   announce 回来 → `notify_live({type:'done', runId, success})` 关实况窗",
    "",
    "    ❌ **MUST NOT** spawn 之后跑 validate_lushu(HTML 还没生成)、`sessions_history` 轮询、`ls -R` 看文件、自己接管 read example-*.html 自己 write 路书(subagent 隔离 context 是设计,不要绕开)。",
    "",
    "Step 4. 风格切换/改版:",
    "    - 替换(「改成 XX 风」) → 父 agent 自己 read 原 HTML 解析行程 + 图片,新风格重新 spawn,覆盖原文件路径(禁止改文件名 / 禁止 delete 再创建)",
    "    - 新增(「再做一版」) → 新 outputPath",
    "",
    "===== 高德 key 反幻觉规则 =====",
    "",
    "`render_map_block({mode:'head'})` 输出的 HTML 段已含真实可用的高德 JS API key 和 securityJsCode,地图能直接渲染。",
    "- ❌ **MUST NOT** 在汇报给用户时说「需要替换 YOUR_AMAP_KEY」「需要填高德 key」「地图 key 待配置」之类",
    "- ❌ **MUST NOT** 自己再写 `<script src='https://webapi.amap.com/maps?v=2.0&key=...'>` — head 段已经引入 SDK,重复引入会 conflict",
    "- ✅ 验证 PASS 后直接告知用户路径,**不要附加任何 key 相关提示** — 那是 LLM 训练数据里高德文档套话的幻觉,与本路书无关",
    "",
    "===== 父 agent 不要 read 的文件(浪费 token,subagent 会自己读) =====",
    "",
    "- subagent guide / references / style-*.md / essentials.md / celia-bridge.md / example-*.html",
    "- 这些已经在 plugin assets 里,subagent 通过 spawn prompt 拿到的绝对路径自己 read",
    "</lushu_priority>",
  ].join("\n");
}
